--- 
- name: Prepare basic env for php apps on all nodes
  hosts: all
  remote_user: vagrant
  sudo: yes
  vars_files:
    - variables.yml
  roles:
    - tools
    - apache
    - php5
    - composer
    - java
    - xvfb
    - selenium
  tasks:
    - name: create directory for bundles' public resources
      file:
        path: /var/www/admin-translatable-bundle/features/fixtures/project/web/bundles
        owner: vagrant
        group: vagrant
        state: directory
    - name: copy admin-bundle's public resources
      file:
        src: /var/www/admin-translatable-bundle/vendor/fsi/admin-bundle/Resources/public
        dest: /var/www/admin-translatable-bundle/features/fixtures/project/web/bundles/fsiadmin
        owner: vagrant
        group: vagrant
        state: link
    - name: copy admin-translatable-bundle's public resources
      file:
        src: /var/www/admin-translatable-bundle/Resources/public
        dest: /var/www/admin-translatable-bundle/features/fixtures/project/web/bundles/fsiadmintranslatable
        owner: vagrant
        group: vagrant
        state: link
    - name: copy ckeditor-bundle's public resources
      file:
        src: /var/www/admin-translatable-bundle/vendor/friendsofsymfony/ckeditor-bundle/Resources/public
        dest: /var/www/admin-translatable-bundle/features/fixtures/project/web/bundles/fosckeditor
        owner: vagrant
        group: vagrant
        state: link
